[manager]
192.168.252.19 node_name=caerus-edge

[edge]
192.168.252.19 node_name=caerus-edge

[db]
192.168.252.20 node_name=caerus-db

[app]
192.168.252.22 node_name=caerus-app-1
192.168.252.21 node_name=caerus-app-2

# everything that is not the manager
[workers]
192.168.252.20 node_name=caerus-db
192.168.252.22 node_name=caerus-app-1
192.168.252.21 node_name=caerus-app-2

# role labels applied to the Swarm nodes
[edge:vars]
caerus_role=edge
[db:vars]
caerus_role=db
[app:vars]
caerus_role=app

[swarm:children]
manager
workers

[swarm:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
